name: Deploy ECS

on:
  push:
    branches:
      - stage

env:
  AWS_REGION: <REGION>
  ECR_REPOSITORY: relayer-<ENV>
  ENVIRONMENT: <ENV>

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.ENVIRONMENT }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.ENVIRONMENT }}

      - name: Deploy to Amazon ECS - Relayer 0
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs/task_definition-0_${{ env.ENVIRONMENT }}.json
          service: relayer-service-${{ env.ENVIRONMENT }}-0
          cluster: relayer-${{ env.ENVIRONMENT }}
          wait-for-service-stability: true
